### ISSUE TITLE
interfaceHash reads too far into data 

### ISSUE THREAD

**Issue by anacrolix** [tobgu/peds#7]
`interfaceHash` calls `fmt.Sprintf("%v", x)` which can cause it to read into mutable data triggering the race detector. The hashing used by Go's built-in `map` key types would be more appropriate (for instance pointer types would just use a hash of the pointer value). I tried to implement this using Go's internal `interhash`, but it just triggers `nil` deference errors that I couldn't figure out.

**Comment by anacrolix** [comment]
Here's how I tried to use `interhash`: https://github.com/anacrolix/peds/commit/70355c20be5501e8405320a3442706c4aefa6833

**Comment by tobgu** [comment]
Hi,

Great thinking! I think the problem was that it is an empty interface,
which is a special case in the runtime. So, you need to use
nilinterhash instead.
See
https://github.com/teh-cmc/go-internals/blob/master/chapter2_interfaces/README.md#the-empty-interface

I pushed a new commit on master with the update:
https://github.com/tobgu/peds/commit/80d0820d0125df66b8173ed22086619c4ad0a33d

Please let me know what the race detector thinks.

Thanks!
// Tobias

Den fre 25 okt. 2019 kl 02:42 skrev Matt Joiner <notifications@github.com>:

**Comment by anacrolix** [comment]
The race detector seems happy, and all my tests are passing. I'm not sure why it needed to handle the `nil` case.

**Comment by tobgu** [comment]
I think the problem is that eface does not have the tab element that is
present on iface so interhash would crash on line 142 here:
https://golang.org/src/runtime/alg.go


Den fre 25 okt. 2019 kl 12:29 skrev Matt Joiner <notifications@github.com>:

**Comment by anacrolix** [comment]
Fantastic, thanks!
